### ISSUE TITLE
Values to add to the expense table

### ISSUE THREAD

**Issue by kil-jonluc** [kil-jonluc/ExpenseProjectDBSchema#5]
Need a few new fields on the expenses table
1. value that links the user to the the expense  
2. With Employer - meaning that the user has submitted expense cannot edit it without it being released back to the user from the employer The employer can approve it, deny it, or send it back to the user with a note. 
3. Under Review - A tag for the employer that indicates to the user that the employer is looking at the expense
4. Approved - Employer approved and the user should be getting paid
5. Denied - not valid expense per employer 
6. With User - status that the expenses it is in until it gets submitted to the Employer or when the Employer sends it back to the user to work on
7. field to store receipt image
8. Description section where the employer can write notes to the user 
9. A description section where the user can communicate with the employer.

**Comment by townsendtechllc** [comment]
Partially completed with most recent PR
